language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer global require satooshi/php-coveralls
#  - composer update --dev --quiet

script:
  - phpunit

after_script:
  - coveralls
